### ISSUE TITLE
ALKiln: Show devs how to automate making new issue on test failure

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#209]
The code for creating an issue on failure with a link to the action itself:
```yml
      - name: If tests failed create an issue
        if: ${{ failure() }}
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: ALKiln tests failed
          body: |
            An ALKiln test failed. See the action at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          labels: |
            bug
```

They can just add it to the bottom of their workflow in `.github/workflows/run_form_tests.yml.
Related to https://github.com/SuffolkLITLab/ALKiln/issues/469
