### ISSUE TITLE
ALKiln: document setting arbitrary env vars

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#229]
[Ignore the below method. Discussion on how to do this, with [linked proof](https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/blob/main/.github/workflows/kiln_tests.yml), is at https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/282#discussion_r960708813]

---

A la https://github.com/plocket/docassemble-CompositeActionsTest/blob/v4_log_in/.github/workflows/run_form_tests.yml#L23-L29

```yml
    steps:
      - uses: actions/checkout@v2
      - name: Set env vars
        run: |
          echo "EMAIL=${{ secrets.PLAYGROUND_EMAIL }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PLAYGROUND_PASSWORD }}" >> $GITHUB_ENV
        shell: bash
```
