### ISSUE TITLE
ALKiln: Simpler way of setting env vars

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#285]
A different and a bit easier to read way of settings these that I've gotten to work is adding this section above the job part of the workflow:

```yml

env:
  TYLER_EMAIL: ${{ secrets.TYLER_EMAIL }}
  TYLER_PASSWORD: ${{ secrets.TYLER_PASSWORD }}
  PROSE_EMAIL: ${{ secrets.PROSE_EMAIL }}
  PROSE_PASSWORD: ${{ secrets.PROSE_PASSWORD }}
```

I don't remember if there were any downsides, it does seem to correctly set the vars in the test though.

_Originally posted by @BryceStevenWilley in https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/282#discussion_r957718172_

> Discussion on how to do this, with [linked proof](https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/blob/main/.github/workflows/kiln_tests.yml), is at https://github.com/SuffolkLITLab/docassemble-AssemblyLine-documentation/pull/282#discussion_r960708813. Maybe the trouble I experienced was in the composite action itself.
