### ISSUE TITLE
ALKiln: Add example code for triggering tests on PR

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine-documentation#382]
```yml
on:
  push:
  pull_request_target:
  workflow_dispatch:
    #etc.
```
